apiVersion: v1
kind: Secret
metadata:
  name: tunnel-credentials
  namespace: cloudflare
type: Opaque
stringData:
  credentials.json: |
    {"AccountTag":"70bb4330aeae9769fe3c30a1e167a06d","TunnelSecret":"QEvKZYdZKoTrx6/b63nLuAFsjdb0b3q2LNI5MDxEGo0=","TunnelID":"243b7d7f-9308-4f01-9b5c-f764b4888b1f","Endpoint":""}
