apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflare
  namespace: cloudflare
spec:
  interval: 5m
  chart:
    spec:
      chart: cloudflare-tunnel
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: cloudflare
        namespace: flux-system
  values:
    cloudflare:
      tunnelName: "flux"
      tunnelId: "9d606950-d84e-42bf-a9a8-0501521b6260"
      secretName: "tunnel-credentials"
      ingress:
        - hostname: "*.raoshahzaib.site"
          service: "https://ingress-nginx-controller.kube-system.svc.cluster.local:443"
          originRequest:
            noTLSVerify: true
    resources:
      limits:
        cpu: "100m"
        memory: "128Mi"
      requests:
        cpu: "100m"
        memory: "128Mi"
    replicaCount: 1