apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: demo-wordpress
  namespace: wordpress
spec:
  interval: 5m
  chart:
    spec:
      chart: wordpress
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values: {}
