apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: wordpress
type: Opaque
data:
  mariadb-root-password: cGFzc3dvcmQ=  # Base64 encoded 'password'
  mariadb-user: d3B1c2Vy  # Base64 encoded 'wpuser'
  mariadb-password: d3BwYXNz  # Base64 encoded 'wppass'
