apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system  # Ensure FluxCD watches this namespace
spec:
  interval: 10m
  chart:
    spec:
      chart: ingress-nginx
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  timeout: 5m
  targetNamespace: kube-system  # Deploy in kube-system namespace
  values:
    controller:
      service:
        type: ClusterIP
      ingressClassResource:
        default: true
