cloudflare:
  tunnelName: "flux"
  tunnelId: "243b7d7f-9308-4f01-9b5c-f764b4888b1f"
  secretName: "tunnel-credentials"
  ingress:
    - hostname: "*.raoshahzaib.site"
      service: "https://ingress-nginx-controller.kube-system.svc.cluster.local:443"
      originRequest:
        noTLSVerify: true

resources:
  limits:
    cpu: "100m"
    memory: "128Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"

replicaCount: 1