apiVersion: v1
kind: Secret
metadata:
  name: tunnel-credentials
  namespace: cloudflare
type: Opaque
data:
  credentials.json: eyJBY2NvdW50VGFnIjoiNzBiYjQzMzBhZWFlOTc2OWZlM2MzMGExZTE2N2EwNmQiLCJUdW5uZWxTZWNyZXQiOiJRRXZLWllkWktvVHJ4Ni9iNjNuTHVBRnNqZGIwYjNxMkxOSTVNRHhFR28wPSIsIlR1bm5lbElEIjoiMjQzYjdkN2YtOTMwOC00ZjAxLTliNWMtZjc2NGI0ODg4YjFmIiwiRW5kcG9pbnQiOiIifQ==
